In [2]:
# check out models
from cgi import test
import numpy as np
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import RepeatedKFold,ShuffleSplit, GroupKFold, LeaveOneGroupOut, train_test_split, GridSearchCV, cross_val_score, KFold, StratifiedKFold
from sklearn.linear_model import Ridge
import scipy.io as sio

y_var = 'normed_motor_scores'
chaco_type = 'chacovol'
subset = 'chronic'
models_tested = ['ridge']
crossval ='2'
results_path = '/Users/emilyolafson/GIT/ENIGMA/enigma_disconnections/results' 
mdl_label = models_tested[0]


atlases = [ 'shen268']
chaco_types = ['chacovol']
crossval_types =['1', '5']
nperms = 25
nperms_null=30

for atlas in atlases:
        for chaco_type in chaco_types:
            for crossval in crossval_types:
                filename = results_path + '/{}_{}_{}_{}_{}_crossval{}'.format(atlas, y_var, chaco_type, subset, mdl_label,crossval)
              
                if crossval == '2':
                    
                    print('two -  Outer CV: Leave-one-site-out')
                    print(correlation[0].shape)
                    print(scores.shape)
                    np.savetxt(filename + '_scores.txt', scores[0], delimiter = ',')
                    for val in correlation[0]:
                        newfile.append(val[0])
                    np.savetxt(filename + '_correlation.txt', newfile, delimiter = ',')                   
                if crossval == '3':
                    print('three - Outer CV: Group K-fold')
                    np.savetxt(filename + '_scores.txt', scores[0], delimiter = ',')
                    for val in correlation[0]:
                        newfile.append(val[0])
                    np.savetxt(filename + '_correlation.txt', newfile, delimiter = ',')
                    print(tmp[0])
                if crossval == '4':
                    print('four - Shuffle')
                    np.savetxt(filename + '_scores.txt', scores[0], delimiter = ',')
                    for val in correlation[0]:
                        newfile.append(val[0])
                    np.savetxt(filename + '_correlation.txt', newfile, delimiter = ',')
                if (crossval == '5') | (crossval=='1'):
                    counter =0
                    for k in range(0, nperms):
                        #print(filename +'_'+ str(k) + '_scores.npy')
                        scores=np.load(filename +'_'+ str(k) + '_scores.npy',allow_pickle=True)
                        correlation = np.load(filename +'_'+ str(k) +'_correlations.npy',allow_pickle=True)
                        np.savetxt(filename +'_'+ str(k) +  '_scores.txt', scores[0], delimiter = ',')
                        newfile=[]
                        for val in correlation[0]:
                            newfile.append(val[0])
                        np.savetxt(filename +'_'+ str(k) +  '_correlations.txt', newfile, delimiter = ',')
                        varimpts=np.load(filename +'_'+ str(k) + '_activation_weights.npy',allow_pickle=True)

                        #print('----')
                        varimpts=varimpts[counter:counter+5,:]
                        print(filename +'_'+ str(k) + '_variable_impts.txt')
                        print(varimpts.shape)
                        sio.savemat(filename +'_'+ str(k) + '_activation_weights.mat', {'varimpts': varimpts})

                       # np.savetxt(filename +'_'+ str(k) + '_activation_weights.txt',varimpts,delimiter = ',')
                        mdl=np.load(filename +'_'+ str(k) + '_model.npy',allow_pickle=True)
                        alphas=[]
                        feats=[]
                        #print(mdl[0][0]['featselect'])
                        for a in range(0,5):
                            alphas.append(mdl[0][a]['ridge'].alpha)
                            feats.append(mdl[0][a]['featselect'].k)
                            
                        np.savetxt(filename +'_'+ str(k) +  '_alphas.txt', alphas, delimiter = ',')
                        np.savetxt(filename +'_'+ str(k) +  '_feats.txt', feats, delimiter = ',')
                        counter=counter+5

                        


                

FileNotFoundError: [Errno 2] No such file or directory: '/Users/emilyolafson/GIT/ENIGMA/enigma_disconnections/results/fs86subj_normed_motor_scores_chacovol_chronic_ridge_crossval1_lesionload_0_scores.npy'

In [9]:
# lesion load of all CST components
atlases = [ 'fs86subj', 'shen268']
chaco_types = ['chacovol']
crossval_types =['1', '5']
nperms = 25
nperms_null=30

for atlas in atlases:
        for chaco_type in chaco_types:
            for crossval in crossval_types:
                filename = results_path + '/{}_{}_{}_{}_{}_crossval{}'.format(atlas, y_var, chaco_type, subset, mdl_label,crossval)
              
                if crossval == '2':
                    
                    print('two -  Outer CV: Leave-one-site-out')
                    print(correlation[0].shape)
                    print(scores.shape)
                    np.savetxt(filename + '_scores.txt', scores[0], delimiter = ',')
                    for val in correlation[0]:
                        newfile.append(val[0])
                    np.savetxt(filename + '_correlation.txt', newfile, delimiter = ',')                   
                if crossval == '3':
                    print('three - Outer CV: Group K-fold')
                    np.savetxt(filename + '_scores.txt', scores[0], delimiter = ',')
                    for val in correlation[0]:
                        newfile.append(val[0])
                    np.savetxt(filename + '_correlation.txt', newfile, delimiter = ',')
                    print(tmp[0])
                if crossval == '4':
                    print('four - Shuffle')
                    np.savetxt(filename + '_scores.txt', scores[0], delimiter = ',')
                    for val in correlation[0]:
                        newfile.append(val[0])
                    np.savetxt(filename + '_correlation.txt', newfile, delimiter = ',')
                if (crossval == '5') | (crossval=='1'):
                    counter =0
                    for k in range(1, nperms):
                        #print(filename +'_'+ str(k) + '_scores.npy')
                        scores=np.load(filename +'_'+ str(k) + '_lesionload_scores.npy',allow_pickle=True)
                        correlation = np.load(filename +'_'+ str(k) +'_lesionload_correlations.npy',allow_pickle=True)
                        np.savetxt(filename +'_'+ str(k) +  '_lesionload_scores.txt', scores[0], delimiter = ',')
                        newfile=[]
                        for val in correlation[0]:
                            newfile.append(val[0])
                        np.savetxt(filename +'_'+ str(k) +  '_lesionload_correlations.txt', newfile, delimiter = ',')
                        #varimpts=np.load(filename +'_'+ str(k) + '_lesionload_activation_weights.npy',allow_pickle=True)

                        #print('----')
                        #varimpts=varimpts[counter:counter+5,:]
                        #print(filename +'_'+ str(k) + '_variable_impts.txt')
                        #print(varimpts.shape)
                        #sio.savemat(filename +'_'+ str(k) + '_activation_weights.mat', {'varimpts': varimpts})

                       # np.savetxt(filename +'_'+ str(k) + '_activation_weights.txt',varimpts,delimiter = ',')
                        #mdl=np.load(filename +'_'+ str(k) + '_model.npy',allow_pickle=True)
                        #alphas=[]
                        #feats=[]
                        #print(mdl[0][0]['featselect'])
                        ##for a in range(0,5):
                         #   alphas.append(mdl[0][a]['ridge'].alpha)
                         #   feats.append(mdl[0][a]['featselect'].k)
                            
                        #np.savetxt(filename +'_'+ str(k) +  '_alphas.txt', alphas, delimiter = ',')
                        #np.savetxt(filename +'_'+ str(k) +  '_feats.txt', feats, delimiter = ',')
                        #counter=counter+5
                        
                     #   fs86subj_normed_motor_scores_chacovol_chronic_ridge_crossval1_1_lesionload_scores.npy


In [13]:
# lesion load of CST only
atlases = [ 'fs86subj', 'shen268']
chaco_types = ['chacovol']
crossval_types =['1', '5']
mdl_label = 'ensemble_reg'
nperms = 25
nperms_null=30

for atlas in atlases:
        for chaco_type in chaco_types:
            for crossval in crossval_types:
                filename = results_path + '/{}_{}_{}_{}_{}_crossval{}'.format(atlas, y_var, chaco_type, subset, mdl_label,crossval)
              
                if crossval == '2':
                    
                    print('two -  Outer CV: Leave-one-site-out')
                    print(correlation[0].shape)
                    print(scores.shape)
                    np.savetxt(filename + '_scores.txt', scores[0], delimiter = ',')
                    for val in correlation[0]:
                        newfile.append(val[0])
                    np.savetxt(filename + '_correlation.txt', newfile, delimiter = ',')                   
                if crossval == '3':
                    print('three - Outer CV: Group K-fold')
                    np.savetxt(filename + '_scores.txt', scores[0], delimiter = ',')
                    for val in correlation[0]:
                        newfile.append(val[0])
                    np.savetxt(filename + '_correlation.txt', newfile, delimiter = ',')
                    print(tmp[0])
                if crossval == '4':
                    print('four - Shuffle')
                    np.savetxt(filename + '_scores.txt', scores[0], delimiter = ',')
                    for val in correlation[0]:
                        newfile.append(val[0])
                    np.savetxt(filename + '_correlation.txt', newfile, delimiter = ',')
                if (crossval == '5') | (crossval=='1'):
                    counter =0
                    for k in range(1, nperms):
                        #print(filename +'_'+ str(k) + '_scores.npy')
                        scores=np.load(filename +'_'+ str(k) + '_lesionload_cst_scores.npy',allow_pickle=True)
                        correlation = np.load(filename +'_'+ str(k) +'_lesionload_cst_correlations.npy',allow_pickle=True)
                        np.savetxt(filename +'_'+ str(k) +  '_lesionload_cst_scores.txt', scores[0], delimiter = ',')
                        newfile=[]
                        for val in correlation[0]:
                            newfile.append(val[0])
                        np.savetxt(filename +'_'+ str(k) +  '_lesionload_cst_correlations.txt', newfile, delimiter = ',')
                        #varimpts=np.load(filename +'_'+ str(k) + '_lesionload_activation_weights.npy',allow_pickle=True)

                        #print('----')
                        #varimpts=varimpts[counter:counter+5,:]
                        #print(filename +'_'+ str(k) + '_variable_impts.txt')
                        #print(varimpts.shape)
                        #sio.savemat(filename +'_'+ str(k) + '_activation_weights.mat', {'varimpts': varimpts})

                       # np.savetxt(filename +'_'+ str(k) + '_activation_weights.txt',varimpts,delimiter = ',')
                        #mdl=np.load(filename +'_'+ str(k) + '_model.npy',allow_pickle=True)
                        #alphas=[]
                        #feats=[]
                        #print(mdl[0][0]['featselect'])
                        ##for a in range(0,5):
                         #   alphas.append(mdl[0][a]['ridge'].alpha)
                         #   feats.append(mdl[0][a]['featselect'].k)
                            
                        #np.savetxt(filename +'_'+ str(k) +  '_alphas.txt', alphas, delimiter = ',')
                        #np.savetxt(filename +'_'+ str(k) +  '_feats.txt', feats, delimiter = ',')
                        #counter=counter+5
                        
                     #   fs86subj_normed_motor_scores_chacovol_chronic_ridge_crossval1_1_lesionload_scores.npy


In [129]:
shen268_normed_motor_scores_chacovol_chronic_ensemble_reg_crossval1_1_lesionload_cst_scores.npy

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]
[0. 1. 2. 3. 4.]
[5. 6. 7. 8. 9.]
[10. 11. 12. 13. 14.]
[15. 16. 17. 18. 19.]
[20. 21. 22. 23. 24.]
[25. 26. 27. 28. 29.]
[30. 31. 32. 33. 34.]
[35. 36. 37. 38. 39.]
[40. 41. 42. 43. 44.]
[45. 46. 47. 48. 49.]
[50. 51. 52. 53. 54.]
[55. 56. 57. 58. 59.]
[60. 61. 62. 63. 64.]
[65. 66. 67. 68. 69.]
[70. 71. 72. 73. 74.]
[75. 76. 77. 78. 79.]
[80. 81. 82. 83. 84.]
[85. 86. 87. 88. 89.]
[90. 91. 92. 93. 94.]
[95. 96. 97. 98. 99.]
[]
[]
[]
[]
[]


In [16]:
# Ensemble models
atlases = [ 'fs86subj', 'shen268']
chaco_types = ['chacovol']
crossval_types =['1', '5']
mdl_label = 'ridge'
nperms = 25
nperms_null=30

for atlas in atlases:
        for chaco_type in chaco_types:
            for crossval in crossval_types:
                filename = results_path + '/{}_{}_{}_{}_{}_crossval{}'.format(atlas, y_var, chaco_type, subset, mdl_label,crossval)
              
                if crossval == '2':
                    
                    print('two -  Outer CV: Leave-one-site-out')
                    print(correlation[0].shape)
                    print(scores.shape)
                    np.savetxt(filename + '_scores.txt', scores[0], delimiter = ',')
                    for val in correlation[0]:
                        newfile.append(val[0])
                    np.savetxt(filename + '_correlation.txt', newfile, delimiter = ',')                   
                if crossval == '3':
                    print('three - Outer CV: Group K-fold')
                    np.savetxt(filename + '_scores.txt', scores[0], delimiter = ',')
                    for val in correlation[0]:
                        newfile.append(val[0])
                    np.savetxt(filename + '_correlation.txt', newfile, delimiter = ',')
                    print(tmp[0])
                if crossval == '4':
                    print('four - Shuffle')
                    np.savetxt(filename + '_scores.txt', scores[0], delimiter = ',')
                    for val in correlation[0]:
                        newfile.append(val[0])
                    np.savetxt(filename + '_correlation.txt', newfile, delimiter = ',')
                if (crossval == '5') | (crossval=='1'):
                    counter =0
                    for k in range(1, nperms):
                        #print(filename +'_'+ str(k) + '_scores.npy')
                        #scores=np.load(filename +'_'+ str(k) + '_ensemble_scores_ensemble.npy',allow_pickle=True)
                        correlation = np.load(filename +'_'+ str(k) +'_ensemble_correlations_ensemble.npy',allow_pickle=True)
                       # np.savetxt(filename +'_'+ str(k) +  '_ensemble_scores_ensemble.txt', scores[0], delimiter = ',')
                        newfile=[]
                        for val in correlation[0]:
                            newfile.append(val[0])
                        np.savetxt(filename +'_'+ str(k) +  '_ensemble_correlations_ensemble.txt', newfile, delimiter = ',')
                        #varimpts=np.load(filename +'_'+ str(k) + '_lesionload_activation_weights.npy',allow_pickle=True)

                        #print('----')
                        #varimpts=varimpts[counter:counter+5,:]
                        #print(filename +'_'+ str(k) + '_variable_impts.txt')
                        #print(varimpts.shape)
                        #sio.savemat(filename +'_'+ str(k) + '_activation_weights.mat', {'varimpts': varimpts})

                       # np.savetxt(filename +'_'+ str(k) + '_activation_weights.txt',varimpts,delimiter = ',')
                        #mdl=np.load(filename +'_'+ str(k) + '_model.npy',allow_pickle=True)
                        #alphas=[]
                        #feats=[]
                        #print(mdl[0][0]['featselect'])
                        ##for a in range(0,5):
                         #   alphas.append(mdl[0][a]['ridge'].alpha)
                         #   feats.append(mdl[0][a]['featselect'].k)
                            
                        #np.savetxt(filename +'_'+ str(k) +  '_alphas.txt', alphas, delimiter = ',')
                        #np.savetxt(filename +'_'+ str(k) +  '_feats.txt', feats, delimiter = ',')
                        #counter=counter+5
                        
                     #   fs86subj_normed_motor_scores_chacovol_chronic_ridge_crossval1_1_lesionload_scores.npy


In [ ]:
shen268_normed_motor_scores_chacovol_chronic_ridge_crossval5_9_ensemble_correlations_ensemble.npy